"""empty message

Revision ID: 3e4037af4ab1
Revises: 342309170fff
Create Date: 2021-05-13 12:02:25.899579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4037af4ab1'
down_revision = '342309170fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('juices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('activities', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('juices')
    # ### end Alembic commands ###
